/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VoluntaryDonor;

import UserInterface.VoluntaryDonor.*;
import Business.EcoSystem;
import Business.Employee.VoluntaryDonor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.VoluntaryDonation.VoluntaryDonorOrganization;
import Business.Organization.VoluntaryDonation.VoluntaryAssistOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VoluntaryAssistWorkRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class RequestVoluntaryTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private VoluntaryDonorOrganization bdo;
    private OrganizationDirectory od;
    private VoluntaryDonor donor;
    /**
     * Creates new form RequestLabTestJPanel
     */
   

    RequestVoluntaryTestJPanel(JPanel userProcessContainer, VoluntaryDonorOrganization organization, OrganizationDirectory od, VoluntaryDonor donor, UserAccount account, Enterprise enterprise) {
         initComponents();
            this.bdo=bdo;
            this.userProcessContainer = userProcessContainer;
            this.donor=donor;
            this.enterprise = enterprise;
            this.account = account;
            valueLabel.setText(enterprise.getName());
            labCB.removeAllItems();
            for(Organization org: od.getOrganizationList())
            {
                if(Organization.Type.VoluntaryAssist.getValue().equals(org.getName()))
                {
                
                    for(Employee e1:org.getEmployeeDirectory().getEmployeeList())
                    {
                        System.out.println("first e1"+e1);
                        labCB.addItem(e1.toString());
                    }
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmitRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labCB = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitRequest.setText("Submit Request");
        btnSubmitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRequestActionPerformed(evt);
            }
        });
        add(btnSubmitRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 89, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });
        add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, -1));

        jLabel2.setText("Availability");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Donor Collector");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel3.setText("Assign To:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        labCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(labCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequestActionPerformed
        
        String message = txtMessage.getText();
        //System.out.println("cobo item"+labCB.getSelectedItem().toString());
         Employee em =null;  
        String emp = labCB.getSelectedItem().toString();
        System.out.println("od size"+enterprise.getOrganizationDirectory().getOrganizationList());
         for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(Organization.Type.VoluntaryAssist.getValue().equals(org.getName()))
            for(UserAccount u:org.getUserAccountDirectory().getUserAccountList())
            {
                if(u.getEmployee().getName().equals(emp))
                {
                    em=u.getEmployee();
                }
               
            }
        }
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(Organization.Type.VoluntaryAssist.getValue().equals(org.getName()))
            for(UserAccount u:org.getUserAccountDirectory().getUserAccountList())
            {
                if(u.getEmployee().getName().equals(em.getName()))
                {
                    WorkQueue wq=u.getWorkQueue();
                VoluntaryAssistWorkRequest request = new VoluntaryAssistWorkRequest();
                request.setMessage(message);
                request.setSender(account);
                request.setStatus("Assigned");
                request.setReceiver(u);
                request.setVoluntaryDonor(donor);
                 wq.getWorkRequestList().add(request);
                 
                
            
        
        
        Organization org1 = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof VoluntaryAssistOrganization){
                org1 = organization;
                break;
            }
        }
        if (org1!=null){
            org1.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("workreq"+org1);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        } }}
    }//GEN-LAST:event_btnSubmitRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VoluntaryDonorWorkAreaJPanel dwjp = (VoluntaryDonorWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitRequest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> labCB;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
