/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VoluntaryDonor;

import UserInterface.VoluntaryDonor.*;
import Business.EcoSystem;
import Business.Employee.VoluntaryDonor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.VoluntaryDonation.VoluntaryDonorOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VoluntaryAssistWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UserInterface.SystemAdmin.ManageNetworkJPanel;

/**
 *
 * @author Malick
 */
public class VoluntaryDonorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private VoluntaryDonorOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    private Network network;
    private OrganizationDirectory od; 
    private VoluntaryDonor voluntaryDonor;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public VoluntaryDonorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,VoluntaryDonorOrganization organization,Enterprise enterprise, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.organization=organization;
        this.enterprise = enterprise;
        this.account = account;
             valueLabel.setText(enterprise.getName());
        populateRequestTable();
        refreshDonorTable();
         od=enterprise.getOrganizationDirectory();
       /* if(enterprise.getEnterpriseType().toString()==Enterprise.EnterpriseType.NPOVoluntary.getValue()){
            
        od=enterprise.getOrganizationDirectory();
            System.out.println("This is Size");
         System.out.println("Size is:" +od.getOrganizationList().size());
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
        refreshDonorTable();*/
        
    } 
    public void refreshDonorTable(){
        int rowcount = donorTable.getRowCount();
        DefaultTableModel model =   (DefaultTableModel) donorTable.getModel();
        /*for(int i = rowcount-1;i>=0;i--)
        {
            model.removeRow(i);
        }*/
         for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(Organization.Type.VoluntaryDonor.getValue().equals(org.getName())){
                 for(VoluntaryDonor bd:org.getEmployeeDirectory().getVoluntaryDonorList()){
                    {
                       Object row[]=new Object[1];
                        row[0]=bd;
                        model.addRow(row);     
              }}
        }
    }
    }
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((VoluntaryAssistWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnAraiseRequest = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labHeading = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        donorTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Availability", "Message", "Assigned Assistance", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(4).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 520, 97));

        btnAraiseRequest.setText("Raise Request");
        btnAraiseRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraiseRequestActionPerformed(evt);
            }
        });
        add(btnAraiseRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 127, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 158, 26));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Donor Collector Request Table");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        labHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labHeading.setText("Donor Collector");
        add(labHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButton1.setText("Add Donor>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        donorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voluntary Donor Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(donorTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 140, 520, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAraiseRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraiseRequestActionPerformed

            int SelectedRow=donorTable.getSelectedRow();
        if(SelectedRow>=0)
        {
            VoluntaryDonor e2 =(VoluntaryDonor) donorTable.getValueAt(SelectedRow,0);
        RequestVoluntaryTestJPanel rtajp = new RequestVoluntaryTestJPanel(userProcessContainer,organization,od,e2,account, enterprise);
        userProcessContainer.add("rtajp",rtajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        userProcessContainer.add("RequestToRecipientJPanel", new RequestVoluntaryTestJPanel(userProcessContainer, userAccount, enterprise));
//        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAraiseRequestActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        populateRequestTable();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddVoluntaryDonor don = new AddVoluntaryDonor(userProcessContainer,od,enterprise,account);
        userProcessContainer.add("AddVoluntaryDonor",don);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAraiseRequest;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTable donorTable;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labHeading;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
