/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VoluntaryDistributor;

import UserInterface.VoluntaryDistributor.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Malick
 */
public class DonorHigherLevelRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    /**
     * Creates new form DonorStateRequestJPanel
     */
    public DonorHigherLevelRequestJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableExcessUnit = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttotalAvailability = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        labEnterpriseValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtAB = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        labLevelValue = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableExcessUnit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City Name", "A", "B", "AB", "O"
            }
        ));
        jScrollPane1.setViewportView(tableExcessUnit);
        if (tableExcessUnit.getColumnModel().getColumnCount() > 0) {
            tableExcessUnit.getColumnModel().getColumn(0).setResizable(false);
            tableExcessUnit.getColumnModel().getColumn(1).setResizable(false);
            tableExcessUnit.getColumnModel().getColumn(2).setResizable(false);
            tableExcessUnit.getColumnModel().getColumn(3).setResizable(false);
            tableExcessUnit.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 420, 70));

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel1.setText("Total Availability");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));
        add(txttotalAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 88, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 127, 30));

        labEnterpriseValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labEnterpriseValue.setText("<value>");
        add(labEnterpriseValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 158, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sending Excess unit to higher level");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));
        add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 88, -1));
        add(txtAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 88, -1));
        add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 88, -1));
        add(txtO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 88, -1));

        jLabel3.setText("Blood type - O");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabel4.setText("Blood type - A");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel5.setText("Blood type - B");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel6.setText("Blood type - AB");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Distributor");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        labLevelValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labLevelValue.setText("<value>");
        add(labLevelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Level :");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
       
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VolunteerDistributorWorkAreaJPanel dwajp = (VolunteerDistributorWorkAreaJPanel) component;
        //dwajp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labEnterpriseValue;
    private javax.swing.JLabel labLevelValue;
    private javax.swing.JTable tableExcessUnit;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAB;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtO;
    private javax.swing.JTextField txttotalAvailability;
    // End of variables declaration//GEN-END:variables
}
