/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.Country.Country;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malick
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private EnterpriseDirectory enterpriseDirectory;
    
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        enterpriseDirectory = new EnterpriseDirectory();
        populateTable();
        populateComboBox();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableJEnterprise.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise;
                row[1] = network.getNetworkCity();
                row[2] = enterprise.getEnterpriseType().getValue();
               
//enterprise.getEnterpriseType().getValue();
                model.addRow(row);
                //System.out.println(enterprise);
            }
        }
    }

    public void populateComboBox() {
        comboCountry.addItem("Select");
        for (Country c : system.getCountryList()) {
            comboCountry.addItem(c.getCountryName());
        }

        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableJEnterprise = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        comboState = new javax.swing.JComboBox<>();
        comboCountry = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        comboEnterpriseType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableJEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network City", "Type", "name"
            }
        ));
        jScrollPane1.setViewportView(tableJEnterprise);
        if (tableJEnterprise.getColumnModel().getColumnCount() > 0) {
            tableJEnterprise.getColumnModel().getColumn(0).setResizable(false);
            tableJEnterprise.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 523, 95));

        jLabel1.setText("City");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 136, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 136, -1));

        submitJButton.setText("Add");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 70, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Enterprise Management");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        comboState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStateActionPerformed(evt);
            }
        });
        add(comboState, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 130, 20));

        comboCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCountryActionPerformed(evt);
            }
        });
        add(comboCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, -1));

        jLabel5.setText("State");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel6.setText("Country");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        comboEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NPOBLOOD", "NPOFOOD", "NPOVOLUNTARY", "NPOFUND" }));
        comboEnterpriseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEnterpriseTypeActionPerformed(evt);
            }
        });
        add(comboEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, -1));

        jLabel3.setText("Enterprise Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        //Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();
      
           //Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) (comboEnterpriseType.getSelectedItem());
        //}
        if(comboEnterpriseType.getSelectedItem().toString().equals("NPOBLOOD")){
            Enterprise.EnterpriseType type = Enterprise.EnterpriseType.NPOBLOOD;
        
        if (network == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = nameJTextField.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        
        enterprise.setEnterpriseType(type);
        
        populateTable();
        
        }
        else if(comboEnterpriseType.getSelectedItem().toString().equals("NPOFOOD")){
            Enterprise.EnterpriseType type = Enterprise.EnterpriseType.NPOFOOD;
        
        if (network == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = nameJTextField.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        
        enterprise.setEnterpriseType(type);
        
        populateTable();
        }
        else if(comboEnterpriseType.getSelectedItem().toString().equals("NPOVOLUNTARY")){
            Enterprise.EnterpriseType type = Enterprise.EnterpriseType.NPOVOLUNTARY;
        
        if (network == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = nameJTextField.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        
        enterprise.setEnterpriseType(type);
        
        populateTable();
        }
        else if(comboEnterpriseType.getSelectedItem().toString().equals("NPOFUND")){
            Enterprise.EnterpriseType type = Enterprise.EnterpriseType.NPOFUND;
        
        if (network == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = nameJTextField.getText();

        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        
        enterprise.setEnterpriseType(type);
        
        populateTable();
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_backJButtonActionPerformed

    private void comboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCountryActionPerformed

        String selectedCountry = (String) comboCountry.getSelectedItem();
        for (Country c : system.getCountryList()) {
            if (c.getCountryName().equalsIgnoreCase(selectedCountry)) {
                comboState.removeAllItems();
                comboState.addItem("Select");
                for (String s : c.getStateNames()) {
                    comboState.addItem(s);
                }
                break;
            }
        }
    }//GEN-LAST:event_comboCountryActionPerformed

    private void comboStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStateActionPerformed
        //networkJComboBox.removeAllItems();
        networkJComboBox.removeAllItems();

        networkJComboBox.addItem("Select");
        String countName = (String) comboCountry.getSelectedItem();
        String stateName = (String) comboState.getSelectedItem();
        if (countName != null && stateName != null) {
            for (Network network : system.getNetworkList()) {
                if (countName.equalsIgnoreCase(network.getNetworkCountry())
                        && stateName.equalsIgnoreCase(network.getNetworkState())) {
                    networkJComboBox.addItem(network);
                }
            }  }
    }//GEN-LAST:event_comboStateActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
       
           //for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
           // comboEnterpriseType.addItem(type);
        //}
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void comboEnterpriseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEnterpriseTypeActionPerformed
        

// TODO add your handling code here:
    }//GEN-LAST:event_comboEnterpriseTypeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tableJEnterprise.getSelectedRow();
            if (selectedRow >= 0){
            Enterprise enterprise = (Enterprise) tableJEnterprise.getValueAt(selectedRow, 0);
                enterpriseDirectory.deleteEnterprise(enterprise);
                populateTable();
                   
                    
                }
            else{
                JOptionPane.showMessageDialog(null, "Please select a row from table to delete", "Warning", JOptionPane.WARNING_MESSAGE);
                
            }



    // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> comboCountry;
    private javax.swing.JComboBox<String> comboEnterpriseType;
    private javax.swing.JComboBox<String> comboState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTable tableJEnterprise;
    // End of variables declaration//GEN-END:variables
}
